[build]
  command = "hugo mod get && hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.150.1"
  NODE_VERSION = "18"

[context.production.environment]
  HUGO_ENV = "production"