
backend:
  name: git-gateway
  branch: main

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "博客文章"
    folder: "content/zh/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "发布时间", name: "date", widget: "datetime"}
      - {label: "描述", name: "description", widget: "string", required: false}
      - label: "标签"
        name: "tags"
        widget: "list"
        required: false
      - {label: "正文", name: "body", widget: "markdown"}
      - {label: "草稿", name: "draft", widget: "boolean", default: true}

  - name: "docs"
    label: "文档页面"
    folder: "content/zh/docs"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "正文", name: "body", widget: "markdown"}

  - name: "community"
    label: "社区页面"
    folder: "content/zh/community"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "正文", name: "body", widget: "markdown"}
